export enum QuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  MULTI_CHOICE = 'MULTI_CHOICE',
  INPUT_TEXT = 'INPUT_TEXT',
  RATING_SCALE = 'RATING_SCALE',
  PICTURE_SELECTION = 'PICTURE_SELECTION',
}
